// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpqxezixcczakkovhtgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwcXhleml4Y2N6YWtrb3ZodGdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5MzAwNTIsImV4cCI6MjA1MjUwNjA1Mn0.2WMPVpyEIn_HUEUEvyKhKvW_fW9k3_8ob6rOks_JfMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);